-- FemboyChat — production Supabase schema (applied to project azriyxvofeceosuoptcm).
--
-- This mirrors what the SupabaseBackend (src/lib/backend/supabase.ts) expects.
-- Secret VALUES (model API keys, webhook secret) live in Supabase Vault and are
-- NOT stored here; see the bottom of this file for how they are referenced.

create extension if not exists pgcrypto;
create extension if not exists pg_net;

-- ── Tables ────────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  uid uuid primary key,                          -- = auth.users.id for real users; fixed ids for seeds/bots
  num_id bigint generated by default as identity,
  username text unique not null,
  name text not null,
  email text unique,
  bio text default '',
  emoji text default '🎀',
  color text default '#ff7ab8',
  status text default '',
  verified boolean default false,
  is_bot boolean default false,
  settings jsonb default '{}'::jsonb,
  last_seen timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.chats (
  id text primary key,
  type text not null,                            -- dm | bot | group | channel | saved
  title text not null,
  username text unique,
  emoji text default '💬',
  color text default '#ff7ab8',
  description text,
  member_uids uuid[] default '{}',
  admin_uids uuid[] default '{}',
  owner_uid uuid,
  verified boolean default false,
  member_count int default 1,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id text references public.chats(id) on delete cascade,
  sender_uid uuid references public.profiles(uid) on delete set null,
  text text default '',
  reply_to_id uuid,
  reactions jsonb default '[]'::jsonb,           -- [{emoji, uids[]}]
  poll jsonb,                                    -- {question, options:[{text, uids[]}], multi}
  sticker text,
  pinned boolean default false,
  deleted boolean default false,
  read_by_uids uuid[] default '{}',
  ttl int,
  edited_ts bigint,
  ts timestamptz default now()
);

create index if not exists messages_chat_ts_idx on public.messages (chat_id, ts asc);
create index if not exists chats_member_uids_idx on public.chats using gin (member_uids);
create index if not exists profiles_username_idx on public.profiles (username);

-- ── Public directory (people, bots, groups, channels) ──────────────────────
create or replace view public.directory as
  select p.uid::text as uid,
         (case when p.is_bot then 'bot' else 'user' end) as kind,
         p.num_id::bigint as num_id, p.username, p.name, p.emoji, p.color,
         coalesce(p.bio, '') as bio, p.verified,
         null::int as members,
         (p.last_seen > now() - interval '5 minutes') as online
  from public.profiles p
  union all
  select c.id as uid, c.type as kind, 0::bigint as num_id,
         coalesce(c.username, '') as username, c.title as name, c.emoji, c.color,
         coalesce(c.description, '') as bio, c.verified,
         c.member_count as members, null::boolean as online
  from public.chats c
  where c.type in ('group', 'channel');

-- ── RLS ─────────────────────────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;

create policy profiles_select on public.profiles for select using (true);
create policy profiles_insert on public.profiles for insert to authenticated with check (uid = auth.uid());
create policy profiles_update on public.profiles for update to authenticated using (uid = auth.uid()) with check (uid = auth.uid());

create policy chats_select on public.chats for select using (true);
create policy chats_insert on public.chats for insert to authenticated with check (owner_uid = auth.uid());
create policy chats_update on public.chats for update to authenticated
  using (owner_uid = auth.uid() or auth.uid() = any(admin_uids))
  with check (owner_uid = auth.uid() or auth.uid() = any(admin_uids));

create policy messages_select on public.messages for select using (
  exists (select 1 from public.chats c where c.id = messages.chat_id and auth.uid() = any(c.member_uids))
);
create policy messages_insert on public.messages for insert to authenticated with check (sender_uid = auth.uid());
create policy messages_update on public.messages for update to authenticated
  using (sender_uid = auth.uid()) with check (sender_uid = auth.uid());

grant select on public.directory to anon, authenticated;

-- Realtime (SupabaseBackend subscribes to message changes)
do $$ begin
  begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.chats; exception when duplicate_object then null; end;
end $$;

-- ── RPCs (called by SupabaseBackend) ────────────────────────────────────
create or replace function public.list_my_chats()
returns setof public.chats language sql security definer stable set search_path = public as $$
  select c.* from public.chats c
  where auth.uid() = any(c.member_uids) or (c.type = 'saved' and c.owner_uid = auth.uid())
  order by coalesce((select max(m.ts) from public.messages m where m.chat_id = c.id), c.created_at) desc
$$;

create or replace function public.open_dm(other uuid)
returns public.chats language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); did text; ch public.chats; o public.profiles;
begin
  if me is null then raise exception 'Authentication required'; end if;
  if other = me then raise exception 'Cannot DM yourself'; end if;
  did := 'dm-' || (select string_agg(x, '~') from (select unnest(array[me::text, other::text]) as x order by x) s);
  select * into ch from public.chats where id = did;
  if found then return ch; end if;
  select * into o from public.profiles where uid = other;
  insert into public.chats (id, type, title, emoji, color, member_uids, admin_uids, created_at)
  values (did, case when coalesce(o.is_bot, false) then 'bot' else 'dm' end,
          coalesce(o.name, 'Чат'), coalesce(o.emoji, '💬'), coalesce(o.color, '#ff7ab8'),
          array[me, other], '{}', now())
  returning * into ch;
  return ch;
end $$;

create or replace function public.join_entity(entity text)
returns public.chats language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); p public.profiles; ch public.chats;
begin
  if me is null then raise exception 'Authentication required'; end if;
  select * into p from public.profiles where uid::text = entity;
  if found then return public.open_dm(p.uid); end if;
  select * into ch from public.chats where id = entity;
  if not found then raise exception 'Entity not found'; end if;
  if not (me = any(ch.member_uids)) then
    update public.chats set member_uids = array_append(member_uids, me), member_count = coalesce(member_count, 0) + 1
      where id = entity returning * into ch;
  end if;
  return ch;
end $$;

create or replace function public.leave_chat(chat text)
returns void language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  update public.chats set member_uids = array_remove(member_uids, me),
    member_count = greatest(0, coalesce(member_count, 1) - 1) where id = chat;
end $$;

create or replace function public.toggle_reaction(message uuid, emoji text)
returns void language plpgsql security definer set search_path = public as $$
declare me text := auth.uid()::text; arr jsonb; el jsonb; uids jsonb; newarr jsonb := '[]'::jsonb; found boolean := false;
begin
  select coalesce(reactions, '[]'::jsonb) into arr from public.messages where id = message;
  for el in select * from jsonb_array_elements(arr) loop
    if el->>'emoji' = emoji then
      found := true; uids := el->'uids';
      if uids @> to_jsonb(array[me]) then
        uids := (select coalesce(jsonb_agg(u), '[]'::jsonb) from jsonb_array_elements_text(uids) u where u <> me);
      else uids := uids || to_jsonb(array[me]); end if;
      if jsonb_array_length(uids) > 0 then newarr := newarr || jsonb_build_object('emoji', emoji, 'uids', uids); end if;
    else newarr := newarr || el; end if;
  end loop;
  if not found then newarr := newarr || jsonb_build_object('emoji', emoji, 'uids', to_jsonb(array[me])); end if;
  update public.messages set reactions = newarr where id = message;
end $$;

create or replace function public.vote_poll(message uuid, option_index int)
returns void language plpgsql security definer set search_path = public as $$
declare me text := auth.uid()::text; p jsonb; multi boolean; opt jsonb; uids jsonb; newopts jsonb := '[]'::jsonb; i int := 0;
begin
  select poll into p from public.messages where id = message;
  if p is null then return; end if;
  multi := coalesce((p->>'multi')::boolean, false);
  for opt in select * from jsonb_array_elements(p->'options') loop
    uids := opt->'uids';
    if i = option_index then
      if uids @> to_jsonb(array[me]) then
        uids := (select coalesce(jsonb_agg(u), '[]'::jsonb) from jsonb_array_elements_text(uids) u where u <> me);
      else uids := uids || to_jsonb(array[me]); end if;
    elsif not multi then
      uids := (select coalesce(jsonb_agg(u), '[]'::jsonb) from jsonb_array_elements_text(uids) u where u <> me);
    end if;
    newopts := newopts || jsonb_build_object('text', opt->>'text', 'uids', uids);
    i := i + 1;
  end loop;
  update public.messages set poll = jsonb_set(p, '{options}', newopts) where id = message;
end $$;

create or replace function public.toggle_pin(message uuid)
returns void language plpgsql security definer set search_path = public as $$
begin update public.messages set pinned = not coalesce(pinned, false) where id = message; end $$;

create or replace function public.mark_read(chat text)
returns void language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  update public.messages set read_by_uids = array_append(read_by_uids, me)
    where chat_id = chat and not (me = any(read_by_uids));
end $$;

grant execute on function public.list_my_chats() to authenticated;
grant execute on function public.open_dm(uuid) to authenticated;
grant execute on function public.join_entity(text) to authenticated;
grant execute on function public.leave_chat(text) to authenticated;
grant execute on function public.toggle_reaction(uuid, text) to authenticated;
grant execute on function public.vote_poll(uuid, int) to authenticated;
grant execute on function public.toggle_pin(uuid) to authenticated;
grant execute on function public.mark_read(text) to authenticated;

-- ── Onboarding: Saved space + FemboyAI DM + auto-join communities ─────────
create or replace function public.fc_onboard_profile()
returns trigger language plpgsql security definer set search_path = public as $$
declare fem uuid := '00000000-0000-4000-8000-000000000002'; did text;
begin
  if NEW.is_bot then return NEW; end if;
  insert into public.chats (id, type, title, emoji, color, member_uids, admin_uids, owner_uid)
  values ('saved-' || NEW.uid::text, 'saved', 'Избранное', '🔖', '#7cc4ff', array[NEW.uid], array[NEW.uid], NEW.uid)
  on conflict (id) do nothing;
  did := 'dm-' || (select string_agg(x, '~') from (select unnest(array[NEW.uid::text, fem::text]) as x order by x) s);
  insert into public.chats (id, type, title, emoji, color, member_uids, admin_uids)
  values (did, 'bot', 'FemboyAI', '🎀', '#ff7ab8', array[NEW.uid, fem], '{}') on conflict (id) do nothing;
  insert into public.messages (chat_id, sender_uid, text)
  select did, fem, 'Приветик, ' || NEW.name || '! 🎀 Я FemboyAI — твой ласковый ути-пути фембойчик. Твой номер аккаунта #' || NEW.num_id || '. Напиши мне что угодно, уии~ 💗'
  where not exists (select 1 from public.messages where chat_id = did);
  update public.chats set member_uids = array_append(member_uids, NEW.uid), member_count = coalesce(member_count, 0) + 1
    where id in ('chan-news', 'grp-lounge') and not (NEW.uid = any(member_uids));
  return NEW;
end $$;

drop trigger if exists fc_onboard on public.profiles;
create trigger fc_onboard after insert on public.profiles
for each row execute function public.fc_onboard_profile();

-- ── FemboyAI server-side auto-reply ───────────────────────────────────────
-- Reads the model key + webhook secret from Vault (values set out-of-band):
--   vault: GEMINI_API_KEY | GROQ_API_KEY | OPENROUTER_API_KEY | GITHUB_MODELS_TOKEN
--   vault: FC_WEBHOOK_SECRET (random; shared between this trigger and the function)
create or replace function public.get_ai_config()
returns jsonb language sql security definer set search_path = '' as $$
  select coalesce(jsonb_object_agg(name, decrypted_secret), '{}'::jsonb)
  from vault.decrypted_secrets
  where name in ('GEMINI_API_KEY', 'GROQ_API_KEY', 'OPENROUTER_API_KEY', 'GITHUB_MODELS_TOKEN')
$$;
create or replace function public.get_fc_webhook_secret()
returns text language sql security definer set search_path = '' as $$
  select decrypted_secret from vault.decrypted_secrets where name = 'FC_WEBHOOK_SECRET' limit 1
$$;
revoke all on function public.get_ai_config() from public, anon, authenticated;
revoke all on function public.get_fc_webhook_secret() from public, anon, authenticated;
grant execute on function public.get_ai_config() to service_role;
grant execute on function public.get_fc_webhook_secret() to service_role;

-- On a new message in a FemboyAI bot chat, call the femboy-ai-fc Edge Function.
create or replace function public.fc_trigger_femboy()
returns trigger language plpgsql security definer set search_path = public as $$
declare fem uuid := '00000000-0000-4000-8000-000000000002'; ch public.chats; secret text;
begin
  if NEW.sender_uid = fem then return NEW; end if;
  select * into ch from public.chats where id = NEW.chat_id;
  if not found or ch.type <> 'bot' or not (fem = any(ch.member_uids)) then return NEW; end if;
  select decrypted_secret into secret from vault.decrypted_secrets where name = 'FC_WEBHOOK_SECRET' limit 1;
  perform net.http_post(
    url := 'https://azriyxvofeceosuoptcm.supabase.co/functions/v1/femboy-ai-fc',
    body := jsonb_build_object('chatId', NEW.chat_id),
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-fc-secret', coalesce(secret, '')),
    timeout_milliseconds := 30000
  );
  return NEW;
end $$;

drop trigger if exists fc_femboy_reply on public.messages;
create trigger fc_femboy_reply after insert on public.messages
for each row execute function public.fc_trigger_femboy();

-- ── Seed community (people, communities, FemboyAI bot) — see repo history ──
-- (Seeded separately; FemboyAI bot uid = 00000000-0000-4000-8000-000000000002)
