/*
  Собственный сценарий установщика (NSIS).

  Стандартный шаблон Tauri — это MUI2: серая шапка, рамка, четыре
  страницы и кнопки внизу. Как его ни крась картинками, это остаётся
  мастер из девяностых. Здесь шаблон свой целиком: один экран, две
  колонки, свои кнопки, прогресс и автозапуск.

  Своя рамка. Системная шапка убирается совсем: именно она тянет весь
  вид назад в прошлое — толстая рамка, чужой заголовок, три кнопки
  управления. Вместо неё свой крестик в углу. Расплата честная: окно
  нельзя таскать мышкой — подпись узнаёт о нажатии только после того,
  как кнопку отпустили, а значит перетаскивания не получится в принципе.
  Окно всё равно открывается по центру экрана и живёт меньше минуты.
  Escape работает: родная кнопка отмены не удалена, а только скрыта.

  Важно про OutFile. Бандлер Tauri запускает makensis из своей временной
  папки (target/release/nsis/x64) и сразу после этого переносит оттуда
  файл с жёстко заданным именем nsis-output.exe в bundle/nsis. Если писать
  установщик по своему абсолютному пути, переносить будет нечего и сборка
  падает на ровном месте: `не удается найти указанный файл (os error 2)`.
  Поэтому имя тут именно такое и без пути — итоговое имя с версией
  подставит сам бандлер.

  Про обратный слэш. В первой версии пути писались прямо в строках, и
  уровни экранирования разъехались: в готовом .nsi оказалось по два слэша
  подряд, отчего установщик показывал путь с двойным слэшем, а ветки
  реестра создавались не там, где нужно. Теперь в тексте сценария вместо
  слэша стоит знак ^, и он заменяется на настоящий слэш ровно один раз,
  уже при записи файла. Ставить в этом файле ^ где-то ещё нельзя.

  Два правила раскладки, оба оплачены кривыми сборками.

  Первое: созданный раньше контрол лежит ВЫШЕ созданного позже. Поэтому
  всё, что работает фоном (левая колонка, подложка поля), создаётся ПОСЛЕ
  своего содержимого, иначе оно его просто закроет.

  Второе: у подписи нет настоящей прозрачности: режим transparent берёт
  цвет родительского диалога, а не соседней картинки и не подложки под
  ней. Поэтому каждой подписи цвет фона задаётся вручную и ровно тот,
  над чем она лежит. По той же причине тут нет ни градиентов, ни
  скруглённых кнопок: поверх картинки текст ляжет цветным прямоугольником.
  Честная плоская геометрия и крупная типографика выглядят лучше, чем
  попытка изобразить скругления там, где их не бывает.

  Кнопки — это подписи со стилем SS_CENTER|SS_CENTERIMAGE|SS_NOTIFY, то
  есть текст стоит по центру и по горизонтали, и по вертикали. Родные
  кнопки Windows не умеют ни своего цвета, ни своего шрифта без полной
  отрисовки владельцем, поэтому в таком экране их нет вовсе.

  Почему генератор, а не готовый .nsi в репозитории: часть путей внутри
  абсолютные, а версия берётся из package.json.

  В тексте сценария море конструкций вида ${If}, поэтому он собран из
  массива обычных строк, а не шаблонной строки: иначе JS попытается
  подставить туда свои переменные.
*/

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))
const version = pkg.version

const outDir = resolve(root, 'src-tauri', 'installer')

const paths = {
  icon: resolve(root, 'src-tauri', 'icons', 'icon.ico'),
  logo: resolve(outDir, 'logo.bmp'),
  exe: resolve(root, 'src-tauri', 'target', 'release', 'femboychat.exe'),
}

const NSI = [
  '; Файл собран scripts/installer-nsi.mjs — правь генератор, а не этот файл.',
  'Unicode true',
  'Name "FemboyChat"',
  'Caption "FemboyChat"',
  '; Имя обязано быть таким: бандлер Tauri ищет рядом с собой nsis-output.exe.',
  'OutFile "nsis-output.exe"',
  'InstallDir "$LOCALAPPDATA^FemboyChat"',
  'InstallDirRegKey HKCU "Software^FemboyChat" "InstallDir"',
  'RequestExecutionLevel user',
  'SetCompressor /SOLID lzma',
  'XPStyle on',
  'BrandingText " "',
  'Icon "@ICON@"',
  'UninstallIcon "@ICON@"',
  'ShowInstDetails nevershow',
  'ShowUninstDetails nevershow',
  '',
  '!include "nsDialogs.nsh"',
  '!include "LogicLib.nsh"',
  '!include "WinMessages.nsh"',
  '',
  '!define APP_EXE "femboychat.exe"',
  '!define APP_VER "@VERSION@"',
  '!define UNINST_KEY "Software^Microsoft^Windows^CurrentVersion^Uninstall^FemboyChat"',
  '',
  '; Палитра та же, что у мессенджера. SetCtlColors ждёт RRGGBB без 0x.',
  '!define C_TEXT FFFFFF',
  '!define C_MUTED 8E97B3',
  '!define C_ACCENT 7C9CFF',
  '!define C_DARK 0F1017',
  '; C_RAIL обязан совпадать с BG в scripts/installer-art.mjs.',
  '!define C_RAIL 151827',
  '!define C_FIELD 1B1F2C',
  '',
  '; Размер окна установщика и ширина левой колонки.',
  '!define WIN_W 680',
  '!define WIN_H 470',
  '',
  '; Стиль подписи, работающей как кнопка: текст по центру по обеим осям.',
  '!define BTN_STYLE 0x00000301',
  '; Текст по центру по горизонтали и текст по середине по высоте.',
  '!define TXT_CENTER 0x00000001',
  '!define TXT_MIDDLE 0x00000200',
  '',
  'Var Dialog',
  'Var LogoCtl',
  'Var LogoImg',
  'Var Rail',
  'Var RailName',
  'Var RailVer',
  'Var RailFoot',
  'Var BtnClose',
  'Var LblHead',
  'Var LblSub',
  'Var LblDirCap',
  'Var LblDirBox',
  'Var LblDir',
  'Var LnkDir',
  'Var ChkDesktop',
  'Var BtnGo',
  'Var BtnCancel',
  'Var FontH1',
  'Var FontH2',
  'Var FontText',
  'Var FontSmall',
  'Var FontBtn',
  'Var FontClose',
  'Var MakeDesktop',
  '',
  'Page custom fcWelcome',
  'Page instfiles "" fcInstShow',
  'UninstPage uninstConfirm',
  'UninstPage instfiles',
  '',
  '; Растянуть окно $1 на всю клиентскую область установщика.',
  'Function fcFillClient',
  '  System::Alloc 16',
  '  Pop $0',
  '  System::Call "user32::GetClientRect(i $HWNDPARENT, i r0)"',
  '  System::Call "*$0(i, i, i .r2, i .r3)"',
  '  System::Free $0',
  '  System::Call "user32::SetWindowPos(i r1, i 0, i 0, i 0, i r2, i r3, i 0x14)"',
  'FunctionEnd',
  '',
  '; Скрыть стандартную обвязку: шапку, линейки, подпись и кнопки.',
  'Function fcHideChrome',
  '  GetDlgItem $0 $HWNDPARENT 1034',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1035',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1036',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1037',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1038',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1039',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1045',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1256',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1028',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 2',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 3',
  '  ShowWindow $0 ${SW_HIDE}',
  'FunctionEnd',
  '',
  'Function .onInit',
  '  InitPluginsDir',
  '  File "/oname=$PLUGINSDIR^logo.bmp" "@LOGO@"',
  '  StrCpy $MakeDesktop 1',
  '',
  '  ; Без WebView2 окно приложения будет пустым, лучше сказать сразу.',
  '  ReadRegStr $0 HKLM "SOFTWARE^WOW6432Node^Microsoft^EdgeUpdate^Clients^{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"',
  '  ${If} $0 == ""',
  '    ReadRegStr $0 HKCU "SOFTWARE^Microsoft^EdgeUpdate^Clients^{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"',
  '  ${EndIf}',
  '  ${If} $0 == ""',
  '    MessageBox MB_YESNO|MB_ICONQUESTION "Для FemboyChat нужен компонент Microsoft Edge WebView2. Открыть страницу загрузки?" IDNO fcSkipWv',
  '    ExecShell "open" "https://developer.microsoft.com/microsoft-edge/webview2/"',
  '    fcSkipWv:',
  '  ${EndIf}',
  'FunctionEnd',
  '',
  '; Окно: без системной шапки, своего размера, по центру экрана.',
  'Function .onGUIInit',
  '  ; Снимаем WS_CAPTION, WS_SYSMENU и WS_THICKFRAME — это 0x00CC0000.',
  '  System::Call "user32::GetWindowLongW(p $HWNDPARENT, i -16) i .r4"',
  '  IntOp $5 0x00CC0000 ~',
  '  IntOp $4 $4 & $5',
  '  System::Call "user32::SetWindowLongW(p $HWNDPARENT, i -16, i r4)"',
  '',
  '  System::Call "user32::GetSystemMetrics(i 0) i .r0"',
  '  System::Call "user32::GetSystemMetrics(i 1) i .r1"',
  '  IntOp $2 $0 - ${WIN_W}',
  '  IntOp $2 $2 / 2',
  '  IntOp $3 $1 - ${WIN_H}',
  '  IntOp $3 $3 / 2',
  '  ; 0x24 = не менять порядок окон + применить новую рамку.',
  '  System::Call "user32::SetWindowPos(i $HWNDPARENT, i 0, i r2, i r3, i ${WIN_W}, i ${WIN_H}, i 0x24)"',
  '',
  '  ; Скруглённые углы и тонкая рамка (Windows 11; на 10 просто ничего).',
  '  System::Call "dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 33, *i 2, i 4)"',
  '  System::Call "dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 34, *i 0x002C2721, i 4)"',
  '  System::Call "dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 20, *i 1, i 4)"',
  'FunctionEnd',
  '',
  'Function fcWelcome',
  '  nsDialogs::Create 1018',
  '  Pop $Dialog',
  '  ${If} $Dialog == error',
  '    Abort',
  '  ${EndIf}',
  '',
  '  Call fcHideChrome',
  '  StrCpy $1 $Dialog',
  '  Call fcFillClient',
  '  SetCtlColors $Dialog ${C_TEXT} ${C_DARK}',
  '',
  '  CreateFont $FontH1 "Segoe UI Semibold" 19 600',
  '  CreateFont $FontH2 "Segoe UI Semibold" 16 600',
  '  CreateFont $FontText "Segoe UI" 10 400',
  '  CreateFont $FontSmall "Segoe UI" 9 400',
  '  CreateFont $FontBtn "Segoe UI Semibold" 11 600',
  '  CreateFont $FontClose "Segoe UI" 12 400',
  '',
  '  ; ── левая колонка: сначала содержимое, фон — в самом конце ──',
  '  ${NSD_CreateBitmap} 69 78 112 112 ""',
  '  Pop $LogoCtl',
  '  ${NSD_SetImage} $LogoCtl "$PLUGINSDIR^logo.bmp" $LogoImg',
  '',
  '  ${NSD_CreateLabel} 0 212 250 26 "FemboyChat"',
  '  Pop $RailName',
  '  SetCtlColors $RailName ${C_TEXT} ${C_RAIL}',
  '  SendMessage $RailName ${WM_SETFONT} $FontH2 1',
  '  ${NSD_AddStyle} $RailName ${TXT_CENTER}',
  '',
  '  ${NSD_CreateLabel} 0 240 250 18 "версия ${APP_VER}"',
  '  Pop $RailVer',
  '  SetCtlColors $RailVer ${C_MUTED} ${C_RAIL}',
  '  SendMessage $RailVer ${WM_SETFONT} $FontSmall 1',
  '  ${NSD_AddStyle} $RailVer ${TXT_CENTER}',
  '',
  '  ${NSD_CreateLabel} 0 424 250 18 "уютно · быстро · своё"',
  '  Pop $RailFoot',
  '  SetCtlColors $RailFoot ${C_MUTED} ${C_RAIL}',
  '  SendMessage $RailFoot ${WM_SETFONT} $FontSmall 1',
  '  ${NSD_AddStyle} $RailFoot ${TXT_CENTER}',
  '',
  '  ; ── правая часть ──',
  '  ${NSD_CreateLabel} 640 14 26 26 "✕"',
  '  Pop $BtnClose',
  '  SetCtlColors $BtnClose ${C_MUTED} ${C_DARK}',
  '  SendMessage $BtnClose ${WM_SETFONT} $FontClose 1',
  '  ${NSD_AddStyle} $BtnClose ${BTN_STYLE}',
  '  ${NSD_OnClick} $BtnClose fcOnCancel',
  '',
  '  ${NSD_CreateLabel} 292 76 340 30 "Установка"',
  '  Pop $LblHead',
  '  SetCtlColors $LblHead ${C_TEXT} ${C_DARK}',
  '  SendMessage $LblHead ${WM_SETFONT} $FontH1 1',
  '',
  '  ${NSD_CreateLabel} 292 114 348 36 "Займёт пару секунд и не потребует прав администратора. Мессенджер откроется сразу после."',
  '  Pop $LblSub',
  '  SetCtlColors $LblSub ${C_MUTED} ${C_DARK}',
  '  SendMessage $LblSub ${WM_SETFONT} $FontSmall 1',
  '',
  '  ${NSD_CreateLabel} 292 180 300 16 "КУДА УСТАНОВИТЬ"',
  '  Pop $LblDirCap',
  '  SetCtlColors $LblDirCap ${C_MUTED} ${C_DARK}',
  '  SendMessage $LblDirCap ${WM_SETFONT} $FontSmall 1',
  '',
  '  ; Сначала содержимое поля, подложка — сразу после него.',
  '  ${NSD_CreateLabel} 306 200 232 42 "$INSTDIR"',
  '  Pop $LblDir',
  '  SetCtlColors $LblDir ${C_TEXT} ${C_FIELD}',
  '  SendMessage $LblDir ${WM_SETFONT} $FontText 1',
  '  ${NSD_AddStyle} $LblDir ${TXT_MIDDLE}',
  '',
  '  ${NSD_CreateLabel} 546 200 92 42 "Изменить"',
  '  Pop $LnkDir',
  '  SetCtlColors $LnkDir ${C_ACCENT} ${C_FIELD}',
  '  SendMessage $LnkDir ${WM_SETFONT} $FontText 1',
  '  ${NSD_AddStyle} $LnkDir ${BTN_STYLE}',
  '  ${NSD_OnClick} $LnkDir fcOnBrowse',
  '',
  '  ${NSD_CreateLabel} 292 200 346 42 ""',
  '  Pop $LblDirBox',
  '  SetCtlColors $LblDirBox ${C_FIELD} ${C_FIELD}',
  '',
  '  ${NSD_CreateCheckbox} 292 262 330 22 "Создать ярлык на рабочем столе"',
  '  Pop $ChkDesktop',
  '  SetCtlColors $ChkDesktop ${C_MUTED} ${C_DARK}',
  '  SendMessage $ChkDesktop ${WM_SETFONT} $FontText 1',
  '  ${NSD_Check} $ChkDesktop',
  '',
  '  ${NSD_CreateLabel} 292 384 222 50 "Установить"',
  '  Pop $BtnGo',
  '  SetCtlColors $BtnGo ${C_DARK} ${C_ACCENT}',
  '  SendMessage $BtnGo ${WM_SETFONT} $FontBtn 1',
  '  ${NSD_AddStyle} $BtnGo ${BTN_STYLE}',
  '  ${NSD_OnClick} $BtnGo fcOnInstall',
  '',
  '  ${NSD_CreateLabel} 526 384 112 50 "Отмена"',
  '  Pop $BtnCancel',
  '  SetCtlColors $BtnCancel ${C_MUTED} ${C_FIELD}',
  '  SendMessage $BtnCancel ${WM_SETFONT} $FontText 1',
  '  ${NSD_AddStyle} $BtnCancel ${BTN_STYLE}',
  '  ${NSD_OnClick} $BtnCancel fcOnCancel',
  '',
  '  ; Фон левой колонки — самым последним, чтобы оказаться под всем.',
  '  ${NSD_CreateLabel} 0 0 250 ${WIN_H} ""',
  '  Pop $Rail',
  '  SetCtlColors $Rail ${C_RAIL} ${C_RAIL}',
  '',
  '  nsDialogs::Show',
  '  ${NSD_FreeImage} $LogoImg',
  'FunctionEnd',
  '',
  'Function fcOnBrowse',
  '  Pop $0',
  '  nsDialogs::SelectFolderDialog "Куда установить FemboyChat" "$INSTDIR"',
  '  Pop $0',
  '  ${If} $0 != error',
  '    StrCpy $INSTDIR $0',
  '    ${NSD_SetText} $LblDir "$INSTDIR"',
  '  ${EndIf}',
  'FunctionEnd',
  '',
  'Function fcOnInstall',
  '  Pop $0',
  '  ${NSD_GetState} $ChkDesktop $MakeDesktop',
  '  SendMessage $HWNDPARENT ${WM_COMMAND} 1 0',
  'FunctionEnd',
  '',
  'Function fcOnCancel',
  '  Pop $0',
  '  SendMessage $HWNDPARENT ${WM_CLOSE} 0 0',
  'FunctionEnd',
  '',
  '; Страница установки: тот же тёмный фон, без списка файлов.',
  'Function fcInstShow',
  '  Call fcHideChrome',
  '  FindWindow $1 "#32770" "" $HWNDPARENT',
  '  Call fcFillClient',
  '  SetCtlColors $1 ${C_TEXT} ${C_DARK}',
  '',
  '  GetDlgItem $0 $1 1016',
  '  ShowWindow $0 ${SW_HIDE}',
  '',
  '  GetDlgItem $0 $1 1006',
  '  SetCtlColors $0 ${C_MUTED} ${C_DARK}',
  '  System::Call "user32::SetWindowPos(i r0, i 0, i 240, i 216, i 300, i 20, i 0x14)"',
  '',
  '  GetDlgItem $0 $1 1004',
  '  System::Call "user32::SetWindowPos(i r0, i 0, i 240, i 246, i 300, i 8, i 0x14)"',
  'FunctionEnd',
  '',
  'Section "FemboyChat"',
  '  SetOutPath "$INSTDIR"',
  '',
  '  ; Если приложение запущено, файл будет занят.',
  '  nsExec::Exec "taskkill /F /IM ${APP_EXE}"',
  '  Pop $0',
  '  Sleep 300',
  '',
  '  File "@EXE@"',
  '  WriteUninstaller "$INSTDIR^uninstall.exe"',
  '',
  '  WriteRegStr HKCU "Software^FemboyChat" "InstallDir" "$INSTDIR"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayName" "FemboyChat"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayVersion" "${APP_VER}"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "Publisher" "kultik1337"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayIcon" "$INSTDIR^${APP_EXE}"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "UninstallString" "$INSTDIR^uninstall.exe"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"',
  '  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify" 1',
  '  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair" 1',
  '',
  '  CreateShortcut "$SMPROGRAMS^FemboyChat.lnk" "$INSTDIR^${APP_EXE}"',
  '  ${If} $MakeDesktop == 1',
  '    CreateShortcut "$DESKTOP^FemboyChat.lnk" "$INSTDIR^${APP_EXE}"',
  '  ${EndIf}',
  '',
  '  SetAutoClose true',
  'SectionEnd',
  '',
  '; После установки сразу открываем мессенджер — без финальной страницы.',
  'Function .onInstSuccess',
  '  Exec "$INSTDIR^${APP_EXE}"',
  'FunctionEnd',
  '',
  'Section "Uninstall"',
  '  nsExec::Exec "taskkill /F /IM ${APP_EXE}"',
  '  Pop $0',
  '  Sleep 300',
  '',
  '  Delete "$INSTDIR^${APP_EXE}"',
  '  Delete "$INSTDIR^uninstall.exe"',
  '  RMDir "$INSTDIR"',
  '',
  '  Delete "$SMPROGRAMS^FemboyChat.lnk"',
  '  Delete "$DESKTOP^FemboyChat.lnk"',
  '',
  '  DeleteRegKey HKCU "${UNINST_KEY}"',
  '  DeleteRegKey HKCU "Software^FemboyChat"',
  'SectionEnd',
  '',
].join('\n')

mkdirSync(outDir, { recursive: true })

// Знак ^ во всём тексте выше означает обратный слэш — см. комментарий в шапке.
const BACKSLASH = String.fromCharCode(92)

const nsi = NSI.split('^')
  .join(BACKSLASH)
  .replace('@ICON@', paths.icon)
  .replace('@ICON@', paths.icon)
  .replace('@LOGO@', paths.logo)
  .replace('@EXE@', paths.exe)
  .replaceAll('@VERSION@', version)

writeFileSync(resolve(outDir, 'installer.nsi'), nsi, 'utf8')

console.log(`\u2713 сценарий установщика: src-tauri/installer/installer.nsi (версия ${version})`)
