/*
  Собственный сценарий установщика (NSIS).

  Стандартный шаблон Tauri — это MUI2: серая шапка, рамка, четыре
  страницы и кнопки внизу. Как его ни крась картинками, это остаётся
  мастером из девяностых. Здесь шаблон собирается целиком свой: вся
  стандартная обвязка прячется, диалог растягивается на всё окно, фон — наша
  картинка, кнопки нарисованы сами: один экран, одна кнопка, прогресс,
  автозапуск — как у современных мессенджеров.

  Почему генератор, а не готовый .nsi в репозитории: все пути внутри
  абсолютные, а версия берётся из package.json. Так сценарий не зависит от
  того, в какую временную папку Tauri его положит перед сборкой, и версия
  никогда не расходится с остальным проектом.

  В тексте сценария море конструкций вида ${If}, поэтому он собран из
  массива обычных строк, а не шаблонной строки: иначе JS попытается
  подставить туда свои переменные.
*/

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))
const version = pkg.version

const outDir = resolve(root, 'src-tauri', 'installer')
const bundleDir = resolve(root, 'src-tauri', 'target', 'release', 'bundle', 'nsis')

const paths = {
  out: resolve(bundleDir, `FemboyChat_${version}_x64-setup.exe`),
  icon: resolve(root, 'src-tauri', 'icons', 'icon.ico'),
  bg: resolve(outDir, 'bg.bmp'),
  exe: resolve(root, 'src-tauri', 'target', 'release', 'femboychat.exe'),
}

const NSI = [
  '; Файл собран scripts/installer-nsi.mjs — правь генератор, а не этот файл.',
  'Unicode true',
  'Name "FemboyChat"',
  'Caption "FemboyChat"',
  'OutFile "@OUT@"',
  'InstallDir "$LOCALAPPDATA\\FemboyChat"',
  'InstallDirRegKey HKCU "Software\\FemboyChat" "InstallDir"',
  'RequestExecutionLevel user',
  'SetCompressor /SOLID lzma',
  'XPStyle on',
  'BrandingText " "',
  'Icon "@ICON@"',
  'UninstallIcon "@ICON@"',
  'ShowInstDetails nevershow',
  'ShowUninstDetails nevershow',
  '',
  '!include "nsDialogs.nsh"',
  '!include "LogicLib.nsh"',
  '!include "WinMessages.nsh"',
  '!include "FileFunc.nsh"',
  '',
  '!define APP_EXE "femboychat.exe"',
  '!define APP_VER "@VERSION@"',
  '!define UNINST_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\FemboyChat"',
  '',
  '; Палитра та же, что у мессенджера.',
  '!define C_TEXT 0xFFFFFF',
  '!define C_MUTED 0x9AA3BD',
  '!define C_ACCENT 0x7C9CFF',
  '!define C_DARK 0x0F1017',
  '',
  'Var Dialog',
  'Var BgCtl',
  'Var BgHandle',
  'Var LblTitle',
  'Var LblSub',
  'Var LblDirCap',
  'Var LblDir',
  'Var LnkDir',
  'Var ChkDesktop',
  'Var BtnGo',
  'Var BtnCancel',
  'Var FontH1',
  'Var FontSmall',
  'Var FontBtn',
  'Var MakeDesktop',
  '',
  'Page custom fcWelcome',
  'Page instfiles "" fcInstShow',
  'UninstPage uninstConfirm',
  'UninstPage instfiles',
  '',
  '; Растянуть окно $1 на всю клиентскую область установщика.',
  'Function fcFillClient',
  '  System::Alloc 16',
  '  Pop $0',
  '  System::Call "user32::GetClientRect(i $HWNDPARENT, i r0)"',
  '  System::Call "*$0(i, i, i .r2, i .r3)"',
  '  System::Free $0',
  '  System::Call "user32::SetWindowPos(i r1, i 0, i 0, i 0, i r2, i r3, i 0x14)"',
  'FunctionEnd',
  '',
  'Function .onInit',
  '  InitPluginsDir',
  '  File "/oname=$PLUGINSDIR\\bg.bmp" "@BG@"',
  '  StrCpy $MakeDesktop 1',
  '',
  '  ; Без WebView2 окно приложения будет пустым, лучше сказать сразу.',
  '  ReadRegStr $0 HKLM "SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"',
  '  ${If} $0 == ""',
  '    ReadRegStr $0 HKCU "SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"',
  '  ${EndIf}',
  '  ${If} $0 == ""',
  '    MessageBox MB_YESNO|MB_ICONQUESTION "Для FemboyChat нужен компонент Microsoft Edge WebView2. Открыть страницу загрузки?" IDNO fcSkipWv',
  '    ExecShell "open" "https://developer.microsoft.com/microsoft-edge/webview2/"',
  '    fcSkipWv:',
  '  ${EndIf}',
  'FunctionEnd',
  '',
  'Function fcWelcome',
  '  nsDialogs::Create 1018',
  '  Pop $Dialog',
  '  ${If} $Dialog == error',
  '    Abort',
  '  ${EndIf}',
  '',
  '  ; Прячем всю стандартную обвязку: шапку, линейку, подпись и кнопки.',
  '  StrCpy $2 "1034 1035 1036 1037 1038 1039 1045 1256 1028 1 2 3"',
  '  GetDlgItem $0 $HWNDPARENT 1034',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1035',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1036',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1037',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1038',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1039',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1045',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1256',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1028',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 1',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 2',
  '  ShowWindow $0 ${SW_HIDE}',
  '  GetDlgItem $0 $HWNDPARENT 3',
  '  ShowWindow $0 ${SW_HIDE}',
  '',
  '  StrCpy $1 $Dialog',
  '  Call fcFillClient',
  '',
  '  ${NSD_CreateBitmap} 0 0 100% 100% ""',
  '  Pop $BgCtl',
  '  ${NSD_SetImage} $BgCtl "$PLUGINSDIR\\bg.bmp" $BgHandle',
  '',
  '  CreateFont $FontH1 "Segoe UI Semibold" 19 600',
  '  CreateFont $FontSmall "Segoe UI" 9 400',
  '  CreateFont $FontBtn "Segoe UI Semibold" 11 600',
  '',
  '  ${NSD_CreateLabel} 126 40 330 30 "FemboyChat"',
  '  Pop $LblTitle',
  '  SetCtlColors $LblTitle ${C_TEXT} transparent',
  '  SendMessage $LblTitle ${WM_SETFONT} $FontH1 1',
  '',
  '  ${NSD_CreateLabel} 128 72 330 18 "Теплый мессенджер для ПК · версия ${APP_VER}"',
  '  Pop $LblSub',
  '  SetCtlColors $LblSub ${C_MUTED} transparent',
  '  SendMessage $LblSub ${WM_SETFONT} $FontSmall 1',
  '',
  '  ${NSD_CreateLabel} 38 150 420 16 "Куда установить"',
  '  Pop $LblDirCap',
  '  SetCtlColors $LblDirCap ${C_MUTED} transparent',
  '  SendMessage $LblDirCap ${WM_SETFONT} $FontSmall 1',
  '',
  '  ${NSD_CreateLabel} 38 168 330 18 "$INSTDIR"',
  '  Pop $LblDir',
  '  SetCtlColors $LblDir ${C_TEXT} transparent',
  '  SendMessage $LblDir ${WM_SETFONT} $FontSmall 1',
  '',
  '  ${NSD_CreateLabel} 376 168 80 18 "Изменить"',
  '  Pop $LnkDir',
  '  SetCtlColors $LnkDir ${C_ACCENT} transparent',
  '  SendMessage $LnkDir ${WM_SETFONT} $FontSmall 1',
  '  ${NSD_AddStyle} $LnkDir 0x00000100',
  '  ${NSD_OnClick} $LnkDir fcOnBrowse',
  '',
  '  ${NSD_CreateCheckbox} 36 202 300 20 "Ярлык на рабочем столе"',
  '  Pop $ChkDesktop',
  '  SetCtlColors $ChkDesktop ${C_MUTED} transparent',
  '  SendMessage $ChkDesktop ${WM_SETFONT} $FontSmall 1',
  '  ${NSD_Check} $ChkDesktop',
  '',
  '  ${NSD_CreateLabel} 38 248 176 42 "Установить"',
  '  Pop $BtnGo',
  '  SetCtlColors $BtnGo ${C_DARK} ${C_ACCENT}',
  '  SendMessage $BtnGo ${WM_SETFONT} $FontBtn 1',
  '  ${NSD_AddStyle} $BtnGo 0x00000301',
  '  ${NSD_OnClick} $BtnGo fcOnInstall',
  '',
  '  ${NSD_CreateLabel} 230 248 120 42 "Отмена"',
  '  Pop $BtnCancel',
  '  SetCtlColors $BtnCancel ${C_MUTED} transparent',
  '  SendMessage $BtnCancel ${WM_SETFONT} $FontSmall 1',
  '  ${NSD_AddStyle} $BtnCancel 0x00000301',
  '  ${NSD_OnClick} $BtnCancel fcOnCancel',
  '',
  '  nsDialogs::Show',
  '  ${NSD_FreeImage} $BgHandle',
  'FunctionEnd',
  '',
  'Function fcOnBrowse',
  '  Pop $0',
  '  nsDialogs::SelectFolderDialog "Куда установить FemboyChat" "$INSTDIR"',
  '  Pop $0',
  '  ${If} $0 != error',
  '    StrCpy $INSTDIR $0',
  '    ${NSD_SetText} $LblDir "$INSTDIR"',
  '  ${EndIf}',
  'FunctionEnd',
  '',
  'Function fcOnInstall',
  '  Pop $0',
  '  ${NSD_GetState} $ChkDesktop $MakeDesktop',
  '  SendMessage $HWNDPARENT ${WM_COMMAND} 1 0',
  'FunctionEnd',
  '',
  'Function fcOnCancel',
  '  Pop $0',
  '  SendMessage $HWNDPARENT ${WM_CLOSE} 0 0',
  'FunctionEnd',
  '',
  '; Страница установки: тот же темный фон, без списка файлов.',
  'Function fcInstShow',
  '  FindWindow $1 "#32770" "" $HWNDPARENT',
  '  Call fcFillClient',
  '  SetCtlColors $1 ${C_TEXT} ${C_DARK}',
  '',
  '  GetDlgItem $0 $1 1016',
  '  ShowWindow $0 ${SW_HIDE}',
  '',
  '  GetDlgItem $0 $1 1006',
  '  SetCtlColors $0 ${C_MUTED} ${C_DARK}',
  '  System::Call "user32::SetWindowPos(i r0, i 0, i 38, i 150, i 420, i 20, i 0x14)"',
  '',
  '  GetDlgItem $0 $1 1004',
  '  System::Call "user32::SetWindowPos(i r0, i 0, i 38, i 178, i 420, i 8, i 0x14)"',
  'FunctionEnd',
  '',
  'Section "FemboyChat"',
  '  SetOutPath "$INSTDIR"',
  '',
  '  ; Если приложение запущено, файл будет занят.',
  '  nsExec::Exec "taskkill /F /IM ${APP_EXE}"',
  '  Pop $0',
  '  Sleep 300',
  '',
  '  File "@EXE@"',
  '  WriteUninstaller "$INSTDIR\\uninstall.exe"',
  '',
  '  WriteRegStr HKCU "Software\\FemboyChat" "InstallDir" "$INSTDIR"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayName" "FemboyChat"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayVersion" "${APP_VER}"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "Publisher" "kultik1337"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "DisplayIcon" "$INSTDIR\\${APP_EXE}"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "UninstallString" "$INSTDIR\\uninstall.exe"',
  '  WriteRegStr HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"',
  '  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify" 1',
  '  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair" 1',
  '',
  '  CreateShortcut "$SMPROGRAMS\\FemboyChat.lnk" "$INSTDIR\\${APP_EXE}"',
  '  ${If} $MakeDesktop == 1',
  '    CreateShortcut "$DESKTOP\\FemboyChat.lnk" "$INSTDIR\\${APP_EXE}"',
  '  ${EndIf}',
  '',
  '  SetAutoClose true',
  'SectionEnd',
  '',
  '; После установки сразу открываем мессенджер — без финальной страницы.',
  'Function .onInstSuccess',
  '  Exec "$INSTDIR\\${APP_EXE}"',
  'FunctionEnd',
  '',
  'Section "Uninstall"',
  '  nsExec::Exec "taskkill /F /IM ${APP_EXE}"',
  '  Pop $0',
  '  Sleep 300',
  '',
  '  Delete "$INSTDIR\\${APP_EXE}"',
  '  Delete "$INSTDIR\\uninstall.exe"',
  '  RMDir "$INSTDIR"',
  '',
  '  Delete "$SMPROGRAMS\\FemboyChat.lnk"',
  '  Delete "$DESKTOP\\FemboyChat.lnk"',
  '',
  '  DeleteRegKey HKCU "${UNINST_KEY}"',
  '  DeleteRegKey HKCU "Software\\FemboyChat"',
  'SectionEnd',
  '',
].join('\n')

mkdirSync(outDir, { recursive: true })
mkdirSync(bundleDir, { recursive: true })

const nsi = NSI.replace('@OUT@', paths.out)
  .replace('@ICON@', paths.icon)
  .replace('@ICON@', paths.icon)
  .replace('@BG@', paths.bg)
  .replace('@EXE@', paths.exe)
  .replaceAll('@VERSION@', version)

writeFileSync(resolve(outDir, 'installer.nsi'), nsi, 'utf8')

console.log(`\u2713 сценарий установщика: src-tauri/installer/installer.nsi (версия ${version})`.replace('${version}', version))
